### ISSUE TITLE
Roadmap in 2024

### ISSUE THREAD

**Issue by kateinoigakukun** [kateinoigakukun/ruby-compute-runtime#9]
This is just a dump of my thoughts, so please don't take it seriously 😅 

- [x] 1. Gemification
    - Done by https://github.com/kateinoigakukun/ruby-compute-runtime/pull/7
- [ ] 2. Adapt to Component Model
    - Will be unblocked after Fastly Compute and Viceroy officially support Component Model
- [ ] 3. Stop building CRuby repeatedly
    - We don't need to re-build CRuby itself after we support dynamic linking. I prototyped dynamic extension library with Component Model [here](https://github.com/kateinoigakukun/ruby-component-linking-demo), which seems promising.
    - Also would be best if we can remove wasi-sdk dependency for the end users by shipping pre-compiled extension library (or statically linked CRuby + extension?)
- [ ] 4. Pre-boot optimization using Wizer
    - In my PoC, it speeds up 50ms -> 5ms to respond to a request
- [ ] 5. Rack support

**Comment by remore** [comment]
I promise I keep my expectations low, but modestly speaking every single item sounds fantastic to me :)
